import { ThemeProvider } from '@/context/themeProvider';
import '../styles/globals.css';
import { Poppins } from 'next/font/google';
import { HeaderProvider } from '@/context/headerProvider';
import { CategoryProvider } from '@/context/categoryProvider';
import Theme from '@/components/params/theme';

export const metadata = {
  title: 'Am Blog',
  description: 'Generated by create next app',
};

const poppins = Poppins({ subsets: ['latin'], weight: '400' });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='pt-br'>
      <body className={poppins.className}>
        <ThemeProvider>
          <HeaderProvider>
            <CategoryProvider>
              <Theme>{children}</Theme>
            </CategoryProvider>
          </HeaderProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
