import './globals.css';
import { Poppins } from 'next/font/google';

export const metadata = {
  title: 'Am Blog',
  description: 'Generated by create next app',
};

const poppins = Poppins({ subsets: ['latin'], weight: '400' });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='pt-br'>
      <body className={`${poppins.className} text-ligth-theme-300 p-4`}>
        {children}
      </body>
    </html>
  );
}
